# kubectl apply -f luis-sanchez-37-secret-fe.yml
apiVersion: v1
kind: Secret
metadata:
  name: luis-sanchez-37-secret-fe
  namespace: luis-sanchez-37-namespace-fe
type: Opaque
data:
  # http://luis-sanchez-37-service-be.luis-sanchez-37-namespace-be.svc.cluster.local:8082
  API_URL: aHR0cDovL2x1aXMtc2FuY2hlei0zNy1zZXJ2aWNlLWJlLmx1aXMtc2FuY2hlei0zNy1uYW1lc3BhY2UtYmUuc3ZjLmNsdXN0ZXIubG9jYWw6ODA4Mg==

# Generar base64 en Linux/Mac: echo -n "valor" | base64
# Generar base64 en PowerShell: [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("valor"))
