name: SonarQube Cloud

on:
  push:
    branches:
      - develop-fe
      - webflux-sql-fe
  pull_request:
    branches:
      - develop-fe
      - webflux-sql-fe

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:

      # =========================================================
      # OBTENER EL CÓDIGO DEL REPOSITORIO
      # =========================================================
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Los clones superficiales deben desactivarse para mayor relevancia del análisis

      # =========================================================
      # EJECUTAR ANÁLISIS DE SONARQUBE | Nota del código: A (excelente) → B → C → D → E (pésimo)
      # =========================================================
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Pipeline Finished
        run: echo "SonarQube Cloud analysis completed. Check results at https://sonarcloud.io"
